[BUG FIX] Section 4 form - update checked items to display correctly in 4.2 upon initial load
globalmangrovewatch/gmw-users pull request #140
Opened 2022-06-23 18:21 UTC by julia-rom

# Description

Fixes bug where checked items were not showing as checked upon initial load (when previous answers exist). 

I added an array which makes managing checked items easier to manage. When an item is checked/unchecked, a ``${label}-${answer}`` gets added or removed from the array. This is way less complicated than filtering through deeply nested items, and much less computationally expensive.
 
[Fixes # (93)](https://github.com/globalmangrovewatch/gmw-users/issues/93)

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Instructions

1. Go to section 4
2.  Check items in 4.2
3. Submit 
4. Refresh to see checked items are still there

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

2022-06-24 19:34 UTC, mmnoo requested changes
Just some small changes

2022-06-24 19:34 UTC, mmnoo commented on mrtt-ui/src/components/CausesOfDeclineForm.js
> +    console.log('types: ', causesOfDeclineTypes)
stray console.log

2022-06-24 19:34 UTC, mmnoo commented on mrtt-ui/src/components/SiteBackgroundForm.js
>    const [stakeholderTypes, setStakeholderTypes] = useState([])
same. can we name this so a comment isnt necessary

2022-06-27 13:01 UTC, julia-rom commented on mrtt-ui/src/components/CausesOfDeclineForm.js
> +    console.log('types: ', causesOfDeclineTypes)
will remove! sorry missed these comments earlier

2022-06-27 15:05 UTC, merged

2022-06-27 16:20 UTC, mmnoo commented on mrtt-ui/src/components/SiteBackgroundForm.js
>    const [stakeholderTypes, setStakeholderTypes] = useState([])
that works, or `isStakeholderTypeChecked`.

2022-06-27 16:20 UTC, mmnoo commented on mrtt-ui/src/components/SiteBackgroundForm.js
>    const [stakeholderTypes, setStakeholderTypes] = useState([])
obv not important. Also saw this is merged. Ignore me.