Feature/75 delete monitoring form
globalmangrovewatch/gmw-users pull request #316
Opened 2022-09-23 23:58 UTC by mmnoo

delete monitoring forms

To test:
- create some forms
- delete each of three types
- see the confirm prompt
- notice the 'Deleting...' status text on the button (prob too fast to see)
- a success toast shows and the app is navigated back to the site overview page

2022-09-26 13:35 UTC, julia-rom commented
noticing conflicts for section 10 now ... lets talk through them today?

2022-09-26 21:58 UTC, mmnoo commented on mrtt-ui/src/components/ButtonDeleteForm.js
> +const StyledButton = styled(ButtonSecondaryWithLoader)`
I updated this to match the delete button from the Landscape form which _I think_ instructed me on. Anyway, consistency at least. Its not red, its teal like everything else.

2022-09-27 14:31 UTC, julia-rom commented
can we have the delete button be a warning or red color?

2022-09-27 14:40 UTC, julia-rom requested changes
looks good, however I would like to see a warning/red colored button for delete

2022-09-27 21:39 UTC, mmnoo commented
Made landscape and monitoring form delete buttons red (delete user from org stayed as is because its an icon button and many rows in a table and feels right not to be red)

2022-09-28 18:17 UTC, merged