Feature/19/countries geojson
globalmangrovewatch/gmw-users pull request #62
Opened 2022-05-16 21:12 UTC by cpapalaz

# Description
code to create json from CSV which filters out countries without mangroves 

Fixes # 19

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

2022-05-18 17:13 UTC, JBurkinshaw requested changes
Nice work. The output looks good - I switched to using it with the map I have seamlessly.

There are a few comments in the code and can you rename it to `mangrove_countries.json` and move it to `gmw-user/mrtt-ui/src/data` to keep it in line with the work I'm doing please?

I'd also suggest formatting the code with [black](https://github.com/psf/black) to make sure everything is following formatting best practices.

2022-05-18 17:13 UTC, JBurkinshaw commented on countries-geojson/countries_geojson.py
> +    print(csvfile)
The `print` statement isn't required. Can you remove it? (I know I left it in my example 😅)

2022-05-18 17:13 UTC, JBurkinshaw commented on countries-geojson/countries_geojson.py
> +from re import M
Is this import being used anywhere? If not, can you remove it?

2022-05-18 17:13 UTC, JBurkinshaw commented on countries-geojson/countries_geojson.py
> +
New lines not required here.

2022-05-18 17:19 UTC, JBurkinshaw commented on countries-geojson/countries_geojson.py
> +jsonFilePath = "/Users/cpapalaz/Desktop/Mangrove_Countries.json"
[Best practice](https://peps.python.org/pep-0008/#function-and-variable-names) in python would be to name variables with snake case (words lowercase and separated by underscores).

Hard coding paths which are specific to your environment isn't ideal. Can you make these relative paths? I know relative paths worked in my example which I wrote in a Jupyter notebook but it's not always straightforward in python. If the suggestion below doesn't work, maybe try something like [this](https://stackoverflow.com/a/918178/3704248).

```suggestion
csv_file_path = "Mangrove_Countries.csv"
json_file_path = "../mrtt-ui/src/data/mangrove_countries.json"
```

2022-05-20 18:25 UTC, JBurkinshaw approved these changes

2022-05-20 18:25 UTC, JBurkinshaw commented on countries-geojson/countries_geojson.py
> +        ) = row
Nice

2022-05-21 17:29 UTC, ghelobytes commented
@JBurkinshaw  @cpapalaz 

Do we want to create a parent folder for these scripts?
I have written some python script to convert the other `csv` to `json` and I can add those here.

Maybe something like this:

```
root/
├── mrtt-ui/
├── scripts/
│   ├── countries-geojson/
│       ├── README.md
│       ├── countries_geojson.py
│   ├── causes-tree/
│       ├── README.md
│       ├── causes_tree.py
│   ├── species-binary/
│       ├── README.md
│       ├── species_binary.py
```

2022-05-24 16:25 UTC, merged

2022-05-24 22:48 UTC, JBurkinshaw commented
> @JBurkinshaw @cpapalaz
> 
> Do we want to create a parent folder for these scripts? I have written some python script to convert the other `csv` to `json` and I can add those here.
> 
> Maybe something like this:
> 
> ```
> root/
> ├── mrtt-ui/
> ├── scripts/
> │   ├── countries-geojson/
> │       ├── README.md
> │       ├── countries_geojson.py
> │   ├── causes-tree/
> │       ├── README.md
> │       ├── causes_tree.py
> │   ├── species-binary/
> │       ├── README.md
> │       ├── species_binary.py
> ```

Sounds good to me. Can you go ahead with the restructure and open a PR?

2022-05-26 23:05 UTC, JBurkinshaw commented
Closes #19